### ISSUE TITLE
Suggestion: format json file with newlines and indents

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#101]
i reckon python had  a very easy way to save json files with white space and new lines
currently, its all in one line and kind of unreadable

which is a bit of a trouble to handle.

last time, the program crashed while downloading several seasonal anime due to network error. and i had to manually change the episode numbers on the files.

i think formatting the json is gonna help a ton with editing episode numbers if any errors occur

**Comment by sdaqo** [comment]
Indeed very easy, looks way better now.
