### ISSUE TITLE
Set one folder as the location for seasonals downloads

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#105]
since im downloading several anime each season, the seasonal anime downloader puts all the downloads in their own separate folders, separated by anime

this makes it difficult to distinguish between shows i watched and shows ive yet to watch

so id like for a way to override the download location.
i reckon this feature used to exist at one point in time in anipy-cli. or i might be mistaking that for ani-cli. im not sure

use a flag like -L (location) for overriding all the download locations to the same directory. its unfortunate that the flag cant be set it to -D (for directory) as the program already takes 2 Ds. it cant take a third D.

thats all

**Comment by sdaqo** [comment]
you can now use -l <location> to override dl location for -d and -S

**Comment by Quicksilver151** [comment]
wait
Seasonal mode still downloads each individual anime into their own folder

**Comment by sdaqo** [comment]
Oh I see, I over read that. I don't really see a  point in changing that tho, it would involve annoying  changes to the code and it shouldn't be that much of a deal. Is there any specific reason you don't want them separated in their own folder?

**Comment by Quicksilver151** [comment]
main reason is because there is a lot of anime and idk which of the shows i did watch and which ones i didnt
normally i used to download all shows on one director
add all to a playlist
finish watching em and then sort manually
now, with anipy-cli i have to de-sort, add all to playlist and sort again

so basically i need it as an indicator for which episodes i have yet to watch. gets confusing and tedious if you have several shows added to seasonals

**Comment by sdaqo** [comment]
Ok I see but I feel you could do that withe the new -l. 

Here is a possible solution
1. Download newest episodes to some folder with -l
2. play them all with `mpv <name to the folder with the subfolders> ` mpv will detect the files  in the subfolders and put them in a playlist automatically
3. mark all the subfolders and copy them to your main download directory so that the folders "merge"

This is one way to solve the problem. Maybe try it. You could also automate this with a little bash script.

**Comment by Quicksilver151** [comment]
# 3 is what ive been doing the whole time

**Comment by Quicksilver151** [comment]
just automated that third part
this will make things less tedious i guess
```py
#!/bin/python3
import os

root = os.path.realpath(".")

folders = []
for path, subdirs, files in os.walk(root):
    for name in subdirs:
        folders.append(os.path.join(path, name))

all_files = []
for folder in folders:
    for path, subdirs, files in os.walk(folder):
        for file in files:
            all_files.append(path+"/"+file)

for file in all_files:
    print("moving: "+file)
    os.system("mv \""+file+"\" "+root)```

**Comment by sdaqo** [comment]
Very nice. I hope you are ok with that. And also I remember, you could  also just use rsync like so: `rsync -a <Main DL folder> <The other folder>`  this will merge them into them Main DL folder.

**Comment by sdaqo** [comment]
Can I close this?
