### ISSUE TITLE
Downloading an episode causes the program to crash

### ISSUE THREAD

**Issue by static7777** [sdaqo/anipy-cli#106]
**Describe the bug**
Downloading an episode crashes the program with the error `"quality" not defined`.

Line 538 of cli.py reads `path = download(self.entry, quality).download()`;
It should be `path = download(self.entry, self.quality).download()`

After the quick fix the program is functional again.

---

**To Reproduce**
1. Find an episode
2. Press "d"
3. Crashes, See error

---

**Expected behavior**
The program should begin to download the episode

---

**Info**
```
Name: anipy-cli
Version: 2.5.11
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /home/eric/.local/lib/python3.10/site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, pyyaml, requests, setuptools, tqdm
Required-by:
```

**Comment by sdaqo** [comment]
Thanks for pointing that out and also fixing it! In the future you could also just do a pull request if you have already found the bug.
