### ISSUE TITLE
History and geckodriver.log are created around the system

### ISSUE THREAD

**Issue by migueldeoleiros** [sdaqo/anipy-cli#11]
Because of the posibility to run the program from any directory both history.txt and geckodriver.log are created in whichever directory you are running the program. The proper and cleaner way to fix this would be to save the files on XDG_CACHE_HOME. 
Check out [this](https://wiki.archlinux.org/title/XDG_Base_Directory) for more info on how XDG base directories work.

**Comment by sdaqo** [comment]
Did you update the tool? This should have been already fixed.

**Comment by migueldeoleiros** [comment]
You are right, I'm an idiot
