### ISSUE TITLE
Randomly creates random extensions for tmp files

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#116]
**Describe the bug**
Randomly creates random extensions for downloaded files. i wish i knew what was happening but its so random and unpredictable

**To Reproduce**
download anime with seasonal mode. or any other mode might also work for downloading but i dont really use anything other than seasonal

**Expected behavior**
download successfully

**What happens**
downloads all video parts with random extensions. and fails to put the files together.

**Info**
tmp folder:
![Screenshot_20230216_064944](https://user-images.githubusercontent.com/56493793/219247721-7bd4e68a-b605-456e-b3f5-40b0645fe8af.png)

funny thing is, all these files contain video data (ts files). i can open em all with mpv

error message:
![Screenshot_20230216_064955](https://user-images.githubusercontent.com/56493793/219247764-ac272486-c77b-4d15-ab53-103a27c69137.png)

**Platform**
 - OS: Kubuntu (Linux)

**possible solutions**
- remove any checks for the extension of filenames in the tmp directory

**Comment by dymattic** [comment]
Interesting, if this happens to all anime, it could mean that gogo tried to make scraping harder.

Your solution might be a feasible workaround.
Maybe there is some way of determining whether the files contain video data without relying on the file extension.

**Comment by sdaqo** [comment]
Idk but I think they fixed it? It doesn't happen anymore, I tried it with the same anime & episode as @Quicksilver151, works as expected.

**Comment by dymattic** [comment]
> Idk but I think they fixed it? It doesn't happen anymore, I tried it with the same anime & episode as @Quicksilver151, works as expected.

I didn't have time to test it yet, but if they fixed it, good!
Maybe we should catch this error if it should happen again, though and display a message of some sort.

**Comment by sdaqo** [comment]
Actually @Quicksilver151, the error you got from ffmpeg does not indicate that it failed because of a wrong file extension (I think ffmpeg does not care). It failed on a .ts file which is  the standard container gogoanime/we use and complained because of invalid data. I don't know what exactly that means though.

**Comment by Quicksilver151** [comment]
> Interesting, if this happens to all anime, it could mean that gogo tried to make scraping harder, but you said it's random.
> 
> I suppose we need to figure out if this is a bug on our end or if it'S a change implemented by gogo.
> 
> Nevertheless:
> 
> Your solution might be a feasible workaround. Maybe there is some way of determining whether the files contain video data without relying on the file extension.

i think it might be for newer anime
since this only happened in seasonals
so i assume the cause of this is the server side issues due to being new uploads

**Comment by Quicksilver151** [comment]
> Actually @Quicksilver151, the error you got from ffmpeg does not indicate that it failed because of a wrong file extension (I think ffmpeg does not care). It failed on a .ts file which is the standard container gogoanime/we use and complained because of invalid data. I don't know what exactly how to fix that though.

that .ts file is the result file of all files combined
i assume the combining process failed without any feedback and resulted in creating a 0 byte file with that name (yes there is one file like that with that name. but its totally empty)

...But when it was time for ffmpeg to convert the combined .ts file to .mp4 and move it out of the `tmp/` folder, it failed because it contains no data

**Comment by sdaqo** [comment]
@Quicksilver151 Sorry I edited your comment, by accident. (why can I do that anyway )

**Comment by Quicksilver151** [comment]
> @Quicksilver151 Sorry I edited your comment, by accident. (why can I do that anyway )

its fine
i can see commit history on messages anyway

why dont other platforms do this? ( *looks at reddit* )

**Comment by Quicksilver151** [comment]
also one more thing
i think this might also be an important detail

the mu8 playlist file also has the random extentions

![image](https://user-images.githubusercontent.com/56493793/219415017-8f765ebd-cfc6-4ed6-97a3-68085be2270e.png)

**Comment by sdaqo** [comment]
Ok, yeah, looking at the function that merges the .ts files [here](https://github.com/sdaqo/anipy-cli/blob/d33d226223fe50c46c909b08061f515701cf070a/anipy_cli/download.py#L179) , we check [here](https://github.com/sdaqo/anipy-cli/blob/d33d226223fe50c46c909b08061f515701cf070a/anipy_cli/download.py#L186) if the part has an .ts extension. @dymattic Do you think we can just remove that check, asking because you wrote this.

**Comment by sdaqo** [comment]
> > @Quicksilver151 Sorry I edited your comment, by accident. (why can I do that anyway )
> 
> its fine i can see commit history on messages anyway
> 
> why dont other platforms do this? ( _looks at reddit_ )

The advantegs of "being" a version controll system, but yeah this should be on other platforms as well.

**Comment by sdaqo** [comment]
Ok so I now implemented the above mentioned fix. As I can't reproduce this exact error, please reopen if anything fails. I just tried changing the extension of one of the files during the download and it worked.

**Comment by Quicksilver151** [comment]
lets see....
![Screenshot_20230217_213531](https://user-images.githubusercontent.com/56493793/219714999-a90d7444-a1b0-40f2-a900-d7291dc730b5.png)


that... was a complete success
![Screenshot_20230217_215146](https://user-images.githubusercontent.com/56493793/219715090-c105ebfb-33fc-4e5b-ba19-1c8185bdf1cb.png)

**Comment by Quicksilver151** [comment]
> @Quicksilver151  🎉 Enjoy Tensei Oujo! I am really liking that one so far.

I actually haven't watched past episode 2. Been a bit too busy to watch anime that I downloaded rn. I am slowly making my way through the list tho

**Comment by dymattic** [comment]
> @Quicksilver151 🎉 Enjoy Tensei Oujo! I am really liking that one so far.

This!

Also sry, for not replying earlier, was busy with work past days ^^
