### ISSUE TITLE
Download broken (response code:502)

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#119]
**Describe the bug**
downloads are no longer working
links may be broken

**To Reproduce**
1. Run anipy-cli in download mode or seasonal mode
2. download any anime

**Expected behavior**
downloads the episode without issue

**Info**
output:
`~> ./anipy_cli.py -Doq 720`
```
***Download Mode***
Downloads are stored in: /home/renderinguser/GIT/anipy-cli/anipy_cli/download
Search: houseki no kuni
Add another search: (y|n)
n

Current:  houseki no kuni
[1] Houseki no Kuni (TV)
[2] Houseki no Kuni (Dub)
Enter Number: 1
anipy-cli: error: requested url not available/blocked: https://ajax.gogo-load.com/ajax/load-list-episode?ep_start=0&ep_end=9999&id=6713: response-code: 502
```
**Platform**
 - OS: Kubuntu (Linux)

is this perhaps due to a change in how gogoanime handles links?
or is it an issue in their servers?

**Comment by sdaqo** [comment]
This is a server problem, can't do anything about it, their site faces the same problem (episode lists don't load)

**Comment by sdaqo** [comment]
They fixed it, closing
