### ISSUE TITLE
.5 episode breaks seasonals download

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#128]
**Describe the bug**
when downloading anime with seasonal mode, program crashes if it encounters x.5 episodes

the anime in question is mashle, which has released episode 6.5 causing the program to crash

**To Reproduce**
1. have mashle in your seasonals list while 6.5 is still the latest episode
2. run seasonals download

**Expected behavior**
- download without any errors

**Info**
terminal output
also btw, i added a print function to print the content of the variable `latest` on seasonal.py line 38
as you can see, the numbers are printed, and it crashes as it reaches mashle
```
[a] Add Anime
[e] Delete one anime from seasonals
[l] List anime in seasonals file
[d] Download newest episodes
[w] Binge watch newest episodes
[q] Quit
Enter option: d
19
7
7
6
7
6
8
6.5
Traceback (most recent call last):
  File "./anipy_cli.py", line 14, in <module>
    main()
  File "./anipy_cli.py", line 8, in main
    cli.run_cli()
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/cli/cli.py", line 37, in run_cli
    cli_class(options=args, rpc_client=rpc_client).run()
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/cli/clis/base_cli.py", line 38, in run
    self.post()
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/cli/clis/seasonal_cli.py", line 28, in post
    menu.run()
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/cli/menus/base_menu.py", line 32, in run
    self.take_input()
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/cli/menus/base_menu.py", line 43, in take_input
    op.callback()
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/cli/menus/seasonal_menu.py", line 111, in download_latest
    latest_urls = self.latest_eps()
  File "/home/renderinguser/GIT/anipy-cli/anipy_cli/seasonal.py", line 40, in latest_eps
    eps_range = list(range(e + 1, latest + 1))
TypeError: 'float' object cannot be interpreted as an integer
```

**Platform**
 - OS: Linux+Gnu -> Debian -> Ubuntu -> *Kubuntu+qtile*

**Additional context**
ive sort of worked around this by `int()`ing the `latest` variable but that only means that download for the .5 episode will be skipped so that other seasonals can be downloaded

**Comment by sdaqo** [comment]
Yeah I see. What we could is using the _load_eps_list function of the epHandler class [here](https://github.com/sdaqo/anipy-cli/blob/master/anipy_cli/url_handler.py#L38). This would return the episode links of all the episodes and we could then index the latest episode the user watched and use everything up to the latest episode. Thing is I currently can't do this as I have no access to a Computer. If anyone wants to, please do go ahead and make a PR for this, will do it later else.

**Comment by Quicksilver151** [comment]
unfortunately i am quite busy, that was why i posted this as an issue in the first place. if this hasnt been done for the next like 4 hours, i might pick it up

**Comment by Quicksilver151** [comment]
done. 
i think
i didnt have to touch the load_eps_list function at all tho
is it too much of a hacky solution?
