### ISSUE TITLE
VLC Player doesn't open

### ISSUE THREAD

**Issue by raymonddong** [sdaqo/anipy-cli#132]
**Describe the bug**
After selecting the episode, the vlc player doesn't open.

**To Reproduce**
1. python anipy_cli.py -p vlc
2. Search katanakaji
3. Select 3
4. Select 7
5. No vlc window is opened. Console just shows

Playing: Kimetsu no Yaiba: Katanakaji no Sato-hen hls | 7/8
[n] Next Episode
[p] Previous Episode
[r] Replay Episode
[s] Select episode
[a] Search for Anime
[i] Print Video Info
[d] Download Episode
[q] Quit
Enter option:

**Expected behavior**
Expected behavior is that vlc opens and plays the episode

**Info**
Name: anipy-cli
Version: 2.7.20
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: C:\Users\raymo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, python-mpv, pyyaml, requests, setuptools, tqdm
Required-by:

**Platform**
 - OS:  Windows
 - VLC: 3.0.18 Vetinari

**Additional context**
I was last able to use -p vlc a couple weeks ago.
Recently I came back and updated to the latest commit and now anipy-cli no longer automatically opens vlc.
I'm still able to copy the stream link and play it in vlc.

**Comment by sdaqo** [comment]
this should be fixed now
