### ISSUE TITLE
Unable to watch anime due to the change of the website

### ISSUE THREAD

**Issue by Gxnum** [sdaqo/anipy-cli#133]
Basically, the website where you get the videos to watch anime, [gogoanime.gg](https://www.gogoanime.gg) has been moved to [gogoanime.vet](https://www.gogoanime.vet)

I believe it's really simple to fix the bug, just change the old website to the new website, because as I see it, the only changed part of the website is the movement from .gg to .vet.

I was just trying to watch One Piece and it showed me this:
```bash
$ anipy-cli

Search: one piece

anipy-cli: error: requested url not available/blocked: https://gogoanime.gg//search.html?keyword=one piece: response-code: 403
```

I use arch linux BTW

**Comment by sdaqo** [comment]
You can change the url in the config. I don't have anything to test it right now, so please report back if this fixes the problem

**Comment by Gxnum** [comment]
It works like a charm (what took me so long)
