### ISSUE TITLE
episode 0 is not downloadable

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#134]
**Describe the bug**
episode #0 is undownloadable
mushoku tensei released episode 0 which the program doesnt seem to know how to handle

**To Reproduce**
![image](https://github.com/sdaqo/anipy-cli/assets/56493793/52da03f1-12d2-471e-b023-00fddfa58eed)

**Additional context**
not even sure how this could be fixable
i personally dont mind downloading an episode 0 manually but i figured i atleast make an error report
maybe add it to a list of "known issues" or something if it cant be fixed

**Comment by sdaqo** [comment]
That's just because the episode isn't there yet. Looking on the website I also can't watch it.

**Comment by Quicksilver151** [comment]
oh damn thats weird

also, new subtle issue. episode 0 doesnt seem to work in seasonal mode

**Comment by sdaqo** [comment]
Sure will look into that

**Comment by sdaqo** [comment]
Should work now. Now you don't put 0 for starting at the beginning but -1
