### ISSUE TITLE
MAL Mode with Apple ID

### ISSUE THREAD

**Issue by raymonddong** [sdaqo/anipy-cli#135]
I signed up for MAL awhile ago with Apple ID. Does that mean I can't use MAL Mode with anipy-cli, since I don't have a password?

**Comment by sdaqo** [comment]
You have to go into your Mal profile settings and set a password there.

**Comment by raymonddong** [comment]
I've created a password. I've updated the config file as well.
However, the config file doesn't seem to read properly
```
in config.py
    def _read_config():
        config_file = Config._get_config_path() / "config.yaml"
        try:
            with config_file.open("r") as conf:
                yaml_conf = yaml.safe_load(conf)
                print(yaml_conf) <-- this is None?
        except FileNotFoundError:
            # There is no config file, create one
            yaml_conf = {}
```
I've already verified that my config location is correct. (windows)

**Comment by raymonddong** [comment]
Not sure what's wrong but the file size is read as 0.
I forced the config file path to somewhere else and it's fine.
Also there's a bug with the open() line.
should be open(config_file, 'r')
Not config_file.open('r')

**Comment by sdaqo** [comment]
Will look into this later. Btw config_file.open('r') is not wrong, the config_file is not a string but a path object.

**Comment by sdaqo** [comment]
Its weird but I can not manage to reproduce this. On Linux and Windows. I know you said you already checked, but do you really have the right config path (that what `anipy-cli --config-path` outputs). If yes also check if your config fields for the mal stuff are correct: `mal_user` and `mal_password`.

**Comment by raymonddong** [comment]
Just running anipy-cli should create a config file right?
I don't see _create_config() called by anywhere.
Because it never did for me, so I've been working with a config.yaml that I pasted into the config location.
I renamed the sample_config.yaml and updated the fields.
I thought it would be fine if I did this, but maybe it's not?

**Comment by raymonddong** [comment]
Dug a little deeper.
I am able to get it to work if the config file points to anywhere else.
But if it's the default location: "C:\Users\raymo\AppData\Local\anipy-cli\config.yaml" the yaml_conf data is the default. It doesn't match the data from the config file.
If I move the file and change the location to the new location, then it's fine.
It works even at "C:\Users\raymo\AppData\Local\config.yaml" and other folders in Local. Not sure why this is happening.
If there's nothing else you can think of, then you can close this issue especially since you can't reproduce it.

**Comment by raymonddong** [comment]
"C:\Users\raymo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\anipy-cli\config.yaml"
Not sure why but info is pulled from here by default. I guess this solves it
