### ISSUE TITLE
[macOS Bug] does not initialize config file properly on a fresh install

### ISSUE THREAD

**Issue by hakushiii** [sdaqo/anipy-cli#137]
**Describe the bug**
Crashes on run after installation because config.yaml is not initialized properly
```
Traceback (most recent call last):
  File "/Users/hakushi/miniconda3/envs/test/bin/anipy-cli", line 5, in <module>
    from anipy_cli.run_anipy_cli import main
  File "/Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages/anipy_cli/__init__.py", line 16, in <module>
    from anipy_cli.query import query
  File "/Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages/anipy_cli/query.py", line 9, in <module>
    base_url = Config().gogoanime_url
               ^^^^^^^^
  File "/Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages/anipy_cli/config.py", line 17, in __init__
    self._create_config() # Create config file
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages/anipy_cli/config.py", line 147, in _create_config
    val = self.__getattribute__(attribute)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages/anipy_cli/config.py", line 25, in download_folder_path
    return self._get_path_value(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages/anipy_cli/config.py", line 124, in _get_path_value
    path = self._get_value(key, fallback, str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages/anipy_cli/config.py", line 131, in _get_value
    value = self._yaml_conf.get(key, fallback)
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
**To Reproduce**
[On macOS]
1. Fresh install of anipy-cli without config files
2. Run

**Expected behavior**
CLI runs

**Info**
```
Name: anipy-cli
Version: 2.7.23
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /Users/hakushi/miniconda3/envs/test/lib/python3.11/site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, python-mpv, pyyaml, requests, setuptools, tqdm
Required-by: 
```

**Platform**
 - OS: macOS 14 Sonoma [Public Beta 4]

**Additional Information**
Program works properly if config.yaml contents is added manually

**Comment by DragonOfShuu** [comment]
I'm sorry, but unfortunately I was unable to recreate your issue. However, I am on an M1 MacBook with the current version of Ventura (13.4.1), as well as using Python 3.11, so maybe that has to do with it.

**Comment by hakushiii** [comment]
Did some tests on the config folder.

Test 1 - deleted the whole config folder:
* anipy-cli created anipy-cli and config.yaml and filled it with necessary configs.

Test 2 - deleted config.yaml:
* anipy-cli created config.yaml and filled it with necessary configs.

Test 3 - empty config.yaml:
* error occurs


result: 
I somehow got an empty config.yaml (i blame Sonoma being a lil' shit and causing bugs).


[Feature Request]
* check config.yaml if empty and fill it with default values if it is empty.

**Comment by sdaqo** [comment]
@DragonOfShuu I think the issue lies here in this [commit](https://github.com/sdaqo/anipy-cli/commit/f1db1add5cdd2c2ca87aa8adbca998407ae87c95). You removed the line where it initializes the conf to {} if it is None (empty)

**Comment by DragonOfShuu** [comment]
@hakushiii , thank you for the tests, it has made the problem far clearer. @sdaqo , thanks lol, I wasn't aware that `yaml.safe_load(conf)` could return straight up `None` if it couldn't find anything in the configuration file. I'm putting together a fix right now.
