### ISSUE TITLE
Windows enviroment variables dont work

### ISSUE THREAD

**Issue by Darkcarnage23** [sdaqo/anipy-cli#139]
**Describe the bug**
The program does not really register windows enviroment variables such as %USERPROFILE%

**To Reproduce**
Set  ``download_folder_path`` to ``download_folder_path: "%USERPROFILE%/AppData/Local/anipy-cli/downloads/common"`` and it'll just create a %USERPROFILE% in your c:\users\user\ directory

**Expected behavior**
for it to  resolve to that directory

**Info**
Post your output of `pip show anipy-cli`
```
Name: anipy-cli
Version: 2.7.23
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: C:\Users\user\AppData\Roaming\Python\Python311\site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, python-mpv, pyyaml, requests, setuptools, tqdm
Required-by:
```

**Platform**
 - OS:  Windows

**Additional context**
Doing some messing around, it seems to work better if self.dl_path uses ``os.path.expandvars(Config().download_folder_path)`` then the issue is resolved but not fully aware the consequences for said change

**Comment by sdaqo** [comment]
I don't know if I want to do that but in the meantime you can use '~' to indicate user profile path

**Comment by DragonOfShuu** [comment]
It's a little bit more complicated than just changing the `dl_path`. Fortunately, that complication allows us to add this kind of compatibility to all paths used in the config file XD. I'm going to make a pull request in just a moment that lets you use environment vars, and your enlightenment on `os.path.expandvars()` is much appreciated.
