### ISSUE TITLE
[API] Episodes that don't exist get sys.exit() instead of just raising an exception

### ISSUE THREAD

**Issue by Bratah123** [sdaqo/anipy-cli#143]
**Describe the bug**
When attempting to download a non-existent episode from an anime, it'll call [sys.exit()](https://github.com/sdaqo/anipy-cli/blob/94bdf3ef0061e4a3f7b25d03f423f94696a3166b/anipy_cli/url_handler.py#L85) instead of just raising an exception.
For CLI tooling I think this is fine, but for API usage, it might be better for developers to have access to this knowledge via an Exception and be able to do their own error handling (Rather than having to catch SystemExit Exceptions)

Script I used to test this:

```py
 if __name__ == '__main__':
    # Caches the queries and entry to save time during bulk downloads
    try:
        downloader = AnimeDownloader("Tate no Yuusha no Nariagari 3rd Season", 1)
        downloader.download()
    except Exception as e:
        print(str(e))
    print("Finished downloading episodes.")
```
Anime Downloader is just a wrapper I wrote that downloads a given anime and episode.

**To Reproduce**
1. Use API to download `Tate no Yuusha no Nariagari 3rd Season` Episode 1 (which currently doesn't exist at the time I'm writing this)

**Expected behavior**
After the url_handler fails to find the episode, it should `raise Exception` to notify API users of it, without terminating their process.

**Info**
![image](https://github.com/sdaqo/anipy-cli/assets/58405975/faf25ee7-c7da-41e8-a4c0-3d0cd40a6055)

**Platform**
 - OS: 
   - Ubuntu
   - Windows

This error happens on both OS

**Additional context**
Perhaps there's some fundamental knowledge I'm missing out on regarding the sys.exit() call. If so I would love some clarification! Thanks for the library and all the hard work!

**Workarounds**
You can except SystemExit (BaseException) to handle this without exiting your process.
```py
if __name__ == '__main__':
    # Caches the queries and entry to save time during bulk downloads
    try:
        downloader = AnimeDownloader("Tate no Yuusha no Nariagari 3rd Season", 1)
        downloader.download()
    except Exception as e:
        print(str(e))
    except SystemExit as se:
        # Do something here
        # This may interfere with real SystemExit calls
        pass
    print("Finished downloading episodes.")
 ```

**Comment by sdaqo** [comment]
Hi! The api side of things is not perfect, I know. I am planning to rewrite parts of the core functionality as I did with the player and cli, trying to seperate Frontend and Backend a little bit more. For now you will have to workaround this issue, I am sorry :(.

**Comment by Bratah123** [comment]
> Hi! The api side of things is not perfect, I know. I am planning to rewrite parts of the core functionality as I did with the player and cli, trying to seperate Frontend and Backend a little bit more. For now you will have to workaround this issue, I am sorry :(.

Thanks, the issue post has the workaround for this for anyone else who has this very specific problem. I'll keep this issue open for other developers who ran into this very niche problem. Feel free to close it though!

**Comment by sdaqo** [comment]
@Bratah123 Soooo, after a considerable amount of time I have finally finished the api rewrite. Please read the docs: https://sdaqo.dev/anipy-cli/getting-started-api/ because the new api is completely different.
I will close this now as this should be resolved!

**Comment by Bratah123** [comment]
Wow that's insane!

Thanks for everything, i'm going to update things from my side now
