### ISSUE TITLE
Cleaner Documention

### ISSUE THREAD

**Issue by 0xYami** [sdaqo/anipy-cli#151]
### Documentation Improvement Suggestions

The existing documentation for [anipy-cli](https://github.com/sdaqo/anipy-cli/blob/master/docs/anipycli_as_lib.py) requires refinement to enhance clarity and user-friendliness. Below are detailed suggestions for improvement:

#### General Feedback

1. **Clarity and Explanation:**
   - The documentation predominantly emphasizes what functions can do rather than providing comprehensive guidance on how to use them.
   - A lack of clarity may lead to confusion among developers, making it essential to reevaluate the explanatory approach.

2. **File Format:**
   - The documentation is currently embedded in a `.py` file, restricting its readability to Python syntax. It is recommended to convert the documentation to a `.md` format to improve accessibility and user-friendliness.

#### 1. /docs/anipycli_as_lib.py Line 41

[`LINK`](https://github.com/sdaqo/anipy-cli/blob/master/docs/anipycli_as_lib.py#L41)

```python
# EPISODE HANDLING

# Episode Handling is facilitated through the epHandler class, capable of tasks such as retrieving the latest episode, generating episode links, and obtaining next/previous episodes. 
# Mandatory fields include category_url and ep.
ep_class = anipy_cli.epHandler(entry)
# Retrieve the latest episode
latest_ep = ep_class.get_latest()
# Generate an episode link, returning an entry
entry = ep_class.gen_eplink()
# Retrieve the next episode, yielding an entry
next_ep = ep_class.next_ep()
# Retrieve the previous episode, yielding an entry
prev_ep = ep_class.prev_ep()
# Obtain the original entry
entry = ep_class.get_entry()
```

##### Suggestions:
- Specify the method or approach for developers to retrieve all episodes comprehensively.

#### 2. /docs/anipycli_as_lib.py Line 74

[`LINK`](https://github.com/sdaqo/anipy-cli/blob/master/docs/anipycli_as_lib.py#L74)

```python
# DOWNLOAD

# Download an m3u8/mp4 link:
# this class requires all
# fields of entry to be filled.
# It also requires a quality argument
# in the same form as anipy_cli.videourl.
# You can also enable ffmpeg download
# for m3u8 playlists with `ffmpeg=True`,
# though this is not recommended, only
# use it when the internal downloader fails,
# also note that there is an option in
# config.py for it.
dl_class = anipy_cli.download(entry, "worst", ffmpeg=True)
# downloads an m3u8 or an mp4 link
dl_class.download()
```

##### Suggestions:
- Clarify that the quality argument should be number-based (e.g., `1080`, `720`) rather than text-based.
- Explicitly state which methods developers should utilize and provide illustrative examples.

**Comment by sdaqo** [comment]
While I do agree to most points, this is not a priority as a new API is planned (I do not know when I have time for that but I do plan to) and the docs would have to be rewritten anyway. Please feel free to make a PR for this though, I will gladly accept it!

**Comment by 0xYami** [comment]
> While I do agree to most points, this is not a priority as a new API is planned (I do not know when I have time for that but I do plan to) and the docs would have to be rewritten anyway. Please feel free to make a PR for this though, I will gladly accept it!

Thank you for taking the time to review the suggestions for improving the documentation. I appreciate your consideration and understanding of the current priorities. It's great to hear that a new API is planned, and I completely understand that a documentation rewrite would be more appropriate in that context.

Should I decide to work on a pull request in the future, I'll make sure to align it with the new API changes. If you have any specific guidelines or preferences for documentation contributions, please feel free to share them.

**Comment by sdaqo** [comment]
I will try to make the new code as self-documenting as possible and maybe integrate some docs with Sphinx and Read the Docs but as I said this will have to wait as I am rather busy right now and do not have time for this. I will close the Issue for the time being.
