### ISSUE TITLE
[Suggestions] Episode numbering for sub-10, and extra config to define show_name separators

### ISSUE THREAD

**Issue by Tebrithiel** [sdaqo/anipy-cli#154]
### Suggestion 1: Episode numbering

When downloading episodes that are sub-10, the episode number is returned as a single digit. When used in the filename it results in strange ordering in file explorers and ls commands. Adding a condition to prepend a `0` if the number is a single digit, will prevent episodes like 2 or 3 from being sorted below episode 10. E.g. Episode `2` would become `02` which would sort above `10`

**Sample code**

`download.py`
```python
episode_number = str(self.entry.ep).zfill(2) if self.entry.ep < 10 else self.entry.ep

return file_format.format(
    show_name=show_name,
    episode_number=episode_number,
    quality=self.entry.quality,
)
```

### Suggestion 2: Extra config to define show_name separator

When setting a name for a downloaded file, the user is given no choice in how the name will be joined together. Currently, the separator is set to a singular hyphen. Adding a simple config setting to pass in a desired separator makes it much easier to control the naming scheme for downloaded files and will improve the user experience when passing files into a media server for storage and playback. i.e. `Unnamed-Memory 01.mp4` will become `Unnamed Memory E01.mp4`

**Sample code**

`config.py`
 
```python
@property
def download_name_seperator(self):
    return self._get_value(
        "download_name_seperator", "-", str # Defaults to original hyphen if config not provided
    )
```

`download.py`
```python
@staticmethod
def _get_valid_pathname(name: str):
    WIN_INVALID_CHARS = ["\\", "/", ":", "*", "?", "<", ">", "|", '"']

    if sys.platform == "win32":
        name = "".join(["" if x in WIN_INVALID_CHARS else x for x in name])

    name = "".join(
        [i for i in name if i.isascii()]
    )  # Verify all chars are ascii (eject if not)

    # Clean all white spaces, including tabs and such
    name = str(Config().download_name_seperator).join(name.split()) # Uses the separator defined in config or the default. Ensures it a string before executing join

    return name
```

I have already implemented these changes in my local version and thought they might be valuable to others. Thoughts?

**Comment by sdaqo** [comment]
Thanks for the input! Here are my thoughts:
1. Good idea, will implement this!
2. I am currently working on v3 (a lot of changes there) and already changed this to a space, as I found spaces are not really that problematic and dashes just look bad in file names. I will consider this new option.

Will close this on v3 release

**Comment by sdaqo** [comment]
I implemented the 0-padding, about the seperators, I think I will not add the config option, because I already, as said above, excluded the seperator thing. If you really want seperators you can just edit your download name format and add your seperators (I know this will not be reflected in the anime name, but I think this is no big deal).
If you think otherwise, please tell me!

**Comment by Tebrithiel** [comment]
Yeah, that's no issue. Glad I could help contribute in a small way. I'll keep the separator code that I have locally, since I already need it.

Feel free to close off this "issue" if you no longer need it.
