### ISSUE TITLE
Typo in a comment in the config file

### ISSUE THREAD

**Issue by AxeldeWater** [sdaqo/anipy-cli#156]
A comment in the config file says this: 

`# A list of pairs that define where in the programm which provider`
`# will be used to look up anime. Configurable areas are as follows:`
`# default (and history), download (-D), seasonal (-S), binge (-B) and mal`
`# (-M) The example will show you how it is done!`

'Programm' should be program, it is clearly a typo. 

Initially I wanted to do a pull request by myself, since it is such a minor issue, but I could nowhere find where to change the comments of the config file ;(  The sample config file has completely different comments.

**Comment by sdaqo** [comment]
Hey there, thanks for reporting my atrocious typo habit! :) 

I think I know why you could not find anything, let me walk you through it:
I am working on `api_rewrite` currently, so switch to the branch:
![image](https://github.com/sdaqo/anipy-cli/assets/63876564/8f33b21a-05c8-4e88-8abc-9eba93c160a3)

The file you want to change is this one: https://github.com/sdaqo/anipy-cli/blob/api_rewrite/cli/src/anipy_cli/config.py. The comments are the same as the comments in the code. 

When making the pull request make sure you are merging into `api_rewrite` as this is the branch I am currently working on, after v3 release you can again just commit normally to the main branch.
![image](https://github.com/sdaqo/anipy-cli/assets/63876564/c1041b66-72ee-4607-bb91-5bac1b58b816)

**Comment by AxeldeWater** [comment]
Oh wow...... I was digging and digging and so confused that it was not in the config.py file... apparently it was in another branch even though I knew that this new version was making use of this new branch... beginner mistake I guess. Thank you for showing me my mistake! I'll take the honor of creating the pull request then haha
