### ISSUE TITLE
An Anime with a period (.) in the title causes issues when Downloading.

### ISSUE THREAD

**Issue by S0litaire** [sdaqo/anipy-cli#161]
**Describe the bug**
A certain title is not being downloaded properly as it has a "period" (.) character in the title. 
 
Example : 

Anime title "Kami wa Game ni Ueteiru."
https://myanimelist.net/anime/50869/Kami_wa_Game_ni_Ueteiru
It currently has 7 episodes.
If you download a range of episodes [1-7]  You are only left with a single episode "Kami wa Game ni Ueteiru.mp4" rather than a series of 7.
 
**To Reproduce**

1. anipy-cli -D
2. Enter search term : Kami wa Game ni Ueteiru
3. Press enter to select the only listing
4. Select between sub/dub downloads
5. Enter range to download : 1-7

**Expected behaviour**

I should have a folder with 7 files numbered 01 to 07. 
But their is only a single file with no number.

**Info**

It was installed via pipx and "pip show anipy-cli" throws an error since it wasn't installed via pip.
But running latest version : 3.0.0

**Platform**
tested on 2 platforms:
First
 - OS: Ubuntu 23.10 aarch64
 - Host: Raspberry Pi 5 Model B Rev 1.0  
 - Kernel: 6.5.0-1015-raspi

Second
  - OS: Ubuntu 24.04 LTS x86_64
  -  Kernel: 6.8.0-1005-nvidia

**Additional context**

In previous version the anime could only be downloaded manually via the -D command and they would be saved and numbered correctly.

In the new V3 it also seems to affect the MAL listings, as the title is not added to the user's "mal_list_########.json" or "seasonals.json" files even though it's selected as "currently watching" in the users MAL profile. 
The "not being saved to the local .json files" also happened in the previous version as well.

**Comment by sdaqo** [comment]
should be fixed in 3.0.2 upgrade with `pipx upgrade anipy-cli`

**Comment by S0litaire** [comment]
Thanks,  3.0.2 works fine.
