### ISSUE TITLE
Is is possible to modify the way files are downloaded?

### ISSUE THREAD

**Issue by Codixer** [sdaqo/anipy-cli#162]
I'm interested to know if it's possible to format the final filename of a download. For example, if I could have them only have episode number as it's name, and starting to count up from a number (See mushoku tensei as an example why
)

**Comment by sdaqo** [comment]
Yes that is possible, 
1. open your config file, located here: `anipy-cli --config-path`
2. modify `download_name_format` like this:
```
download_name_format: '{episode_number}'
```

**Comment by Codixer** [comment]
:O

**Comment by sdaqo** [comment]
> So as an example, /anime/<showname>/<season>/<episode>

you can not sperate the showname and seasons, you will always have the season in the showname. For example "Mushoku Tensei Season 2", because that is how they are named on the site we scrape.

**Comment by Codixer** [comment]
Since I use Jellyfin to watch everything

**Comment by sdaqo** [comment]
Maybe try activating this option, this should merge the different seasons into one show, if they are all recognised by jellyfin/your plugins
![image](https://github.com/sdaqo/anipy-cli/assets/63876564/40d24614-ba7e-433a-a736-f466b01022ac)

**Comment by Codixer** [comment]
Oh that works how I intended it to, the episode number just needs to be first

**Comment by sdaqo** [comment]
Well I guess that works. Can I close this now or are there any other problems?

**Comment by Codixer** [comment]
Is it possible to remove the additional folder it creates?

**Comment by sdaqo** [comment]
Well, that is how it currently works. I guess I could put it on my todo list to think about this, especially when using the --location argument. 
But you can always work around this with some bash script.
How about running something like this after the download command:
```shell
#!/bin/bash

# $1 = path where the anime got downloaded (this is the first argument)

# Move all files from the sub folder in the parent one
mv "$1/*/*" "$1"
# Remove the subfolder
rm -R -- "$1/*/"
```
Save this somewhere to `mover.sh` and do `chmod +x mover.sh` 
So with this you could then run (I am using the `-s` flag here to automate it even more, you may omit it):
`anipy-cli -D --search "my hero academia season 2:1-12:sub" --location "/opt/anime/storage/My Hero Academia/Season 2" --ffmpeg && ./path-to-mover.sh "/opt/anime/storage/My Hero Academia/Season 2"`

**Comment by candrapersada** [comment]
how to use in Windows?

**Comment by sdaqo** [comment]
I think this would be the equivalent windows batch script, I have not tested this tho, so you may have to make some changes yourself
```
@echo off
REM %1 = path where the anime got downloaded (this is the first argument)

REM Move all files from the subfolder to the parent folder
for /d %%d in ("%~1\*") do (
    move "%%d\*" "%~1" >nul
)

REM Remove all empty subfolders
for /d %%d in ("%~1\*") do (
    rmdir "%%d" >nul 2>nul
)
```
