### ISSUE TITLE
[Feature Request] Add "Select from history" to the main menu while playing an episode

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#168]
**Describe the the new feature**
While playing an episode (optimally also while using -S mode) there should be a direct way to jump to history selection via `[h] Select from history`

**What problem are you trying to solve?**
I don't want to always have to quit after I finished the newest episode of an anime to return to my history

**Do you have any ideas for implementation?**
Add following implementation to the main menu: `[h] Select from history`

**Comment by sdaqo** [comment]
Ok, will look into it

**Comment by sdaqo** [comment]
Will implement this for the default cli, but I don't see the benefit for the seasonals
