### ISSUE TITLE
[Feature Request] Add "quit-watch-later" to the main menu

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#169]
**Describe the the new feature**
MPV has the ability to resume playback (See [https://mpv.io/manual/master/#resuming-playback](https://mpv.io/manual/master/#resuming-playback) [https://mpv.io/manual/master/#watch-later](https://mpv.io/manual/master/#watch-later) which is always available by default when quitting the player with Shift+Q.

(VLC has a similar feature)

**What problem are you trying to solve?**
There are certain times when you have to stop watching abruptly due to circumstances and want to resume at a later time

**Do you have any ideas for implementation?**
Add following implementation to the main menu: `[qs] Quit save (position)`
Instead of exiting via `q` you tell mpv to exit via `Q` (Shift+q)
(local state directory usually in `~/.local/state/mpv/watch_later/` by default if `--watch-later-dir=<path>` is unset)

**Comment by sdaqo** [comment]
You can just quit mpv yourself and then q the cli.

**Comment by sdaqo** [comment]
Or make mpv save progress by default

**Comment by GreatTeacherOni** [comment]
Yes that's true. But would still be a nice QoL addition. Sometimes I am already inside the menu while the mpv is either in the background or on another virtual desktop and it would be faster to type q+s+Enter than to switch back to mpv and then type Shift+Q. It also gives a visual incentive that there is a quit and save position feature and that way you won't forget it.

**Comment by sdaqo** [comment]
Still, this would much unnecessary complexity for such a little feature. The thing is I can not really "send" keystrokes, except if using the mpv-controlled.
