### ISSUE TITLE
gogoanime url listed as yugenanime.tv in 3.1 documentation

### ISSUE THREAD

**Issue by migueldeoleiros** [sdaqo/anipy-cli#172]
**Describe the bug**
There seems to be a typo in the documentation for version 3.1
gogoanime has it's url listed as yugenanime.

**Additional context**
This is the commit that adds it
[https://github.com/sdaqo/anipy-cli/commit/ad8d37fc9e2dc6a3fd2aed441d3859aebae4a9dc

**Comment by sdaqo** [comment]
You are right let me fix that.

**Comment by sdaqo** [comment]
You were the first one to PR I think, cool that you are still around!

**Comment by migueldeoleiros** [comment]
Yes! the project has progressed so much, It's great!
