### ISSUE TITLE
[Feature Request] Improve the search feature

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#175]
**Describe the new feature**
A little QoL improvement for the search feature, which I got inspiration from ani-cli.

Here I was searching for "blue".
This screenshot shows the output of ani-cli:
![image](https://github.com/sdaqo/anipy-cli/assets/8284970/06eaa09b-c70a-432b-9ae3-53be14694064)

This one shows the output of anipy-cli:
![image](https://github.com/sdaqo/anipy-cli/assets/8284970/2ea47e89-9f85-411d-bbe7-a8999e1cc70a)

Two things I would like to take from ani-cli:
1) The index numbers at the beginning starting from 1
2) The amount of episodes of that anime at the end of the line
small improvements:
- Instead of "1 episodes" (which ani-cli shows) it should show "1 episode" instead though
- if possible show the index numbers and the amount of episodes in a different color (like darker white or grey), so the important stuff is bright but the other information is less visible

**What problem are you trying to solve?**
- You can search by index number, which is sometimes a little bit more comfortable or even faster
- More information/transparency in the search overview

**Do you have any ideas for implementation?**
Check how ani-cli does it. No need to reinvent the wheel

**Comment by sdaqo** [comment]
Index number, ok. 

The other thing will not work, not every Provider gives us the amount of episodes when searching, we could fetch it for each anime but this would make the search very slow.

**Comment by GreatTeacherOni** [comment]
Regarding the "fetch amount of episodes"-part:
How about you fetch that information on the backend and only from one (or maybe one backup) provider?
Would that be doable?

Ani-cli does it like this I think: https://github.com/pystardust/ani-cli/blob/188030f01139acf48f0a3641d11890437cd783b1/ani-cli#L187C1-L193C2

**Comment by sdaqo** [comment]
> How about you fetch that information on the backend and only from one (or maybe one backup) provider?
Would that be doable?
We support gogo and yugen, both do not give us information about the amount of episodes when searching, we only get that if we request that for each individual anime - this takes time. Even if we did have a provider that supports that, it would not make sense to implement this as it would just make the code more complex. 

>  Show the sum of episodes that are shown in the "select episode"-list if that is easier
Again, with this we would need to fetch episodes for each anime individually.

Generally I do not really think this is that useful anyway. You get to see how many episodes the anime has when you select it anyway.
