### ISSUE TITLE
[Feature Request] Add "Change quality" feature in main menu

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#176]
**Describe the the new feature**
While playing a stream and inside the main menu give the ability to change to another quality

Example of ani-cli:
First screenshot shows the main menu which shows the change_quality button
![image](https://github.com/sdaqo/anipy-cli/assets/8284970/8a79717d-e3ed-47b1-b5a8-98ea72d45389)

Second screenshot shows the quality menu
![image](https://github.com/sdaqo/anipy-cli/assets/8284970/2d3d012a-ad55-400e-b7d6-822f2f01d72b)

Small improvement to how ani-cli does it:
- Inside the quality menu there is no way to return to the main menu if you don't choose a quality. That missing element should be added
- At the end of the URL it should show which provider it is, preferably in parentheses (can also be abbreviated)

**What problem are you trying to solve?**
If you want to see the stream in another quality you have to use arguments while starting anipy-cli

**Do you have any ideas for implementation?**
Maybe similar to how ani-cli does it but with the mentioned QoL improvements

**Comment by sdaqo** [comment]
> At the end of the URL it should show which provider it is, preferably in parentheses (can also be abbreviated)

Providers generally work independent from one another in anipy-cli, meaning if you choose an anime from the gogo provider it will always be a anime form the gogo provider. What I want to say is that, there is no need to show the provider because  there is only one.

**Comment by GreatTeacherOni** [comment]
Works like a charm. 🚀 Thank you!
