### ISSUE TITLE
Download Mode incorrectly shows that range is invalid when going from single to double digit

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#179]
**Describe the bug**
Following error appears:
```
Input Episode Range(s) from episodes 1 to 12: 8-12
anipy-cli: error: invalid range: 8-12
```

**To Reproduce**
1. Run `anipy-cli -D`
2. Search for any anime show
4. After dub selection it asks for range. Input a selection starting from a single digit and ending at a double digit, e.g. `8-12`.

**Expected behavior**
Download should start. No error should be thrown.

**Info**
Post your output of `pip show anipy-cli`
I ran anipy-cli from cloned gitrepo (flake.nix / shell.nix) so no pip output available
anipy-cli version: 3.1.5

**Platform**
 - OS: NixOS

**Additional context**
Workaround: Type `08-12` which makes it single digit with preceding 0.

**Comment by sdaqo** [comment]
thanks for the report, fixed
