### ISSUE TITLE
[Feature] Add example command in help to download episode or range of episodes similar to the search function

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#180]
**Describe the the new feature**
Feature to download a certain episode or range of episodes like so: `anipy-cli -d frieren:1-3:sub (-f)` (optional ffmpeg arg)

**What problem are you trying to solve?**
I'd like to download an episode or range of episodes with a single command instead of going through the interactive menu

**Do you have any ideas for implementation?**
Similar to the command `anipy-cli -s <name of anime>:<episode/range of episodes>:<sub/dub>` e.g. `anipy-cli -s frieren:1-3:sub`
implement the feature to download a certain episode or range of episodes like so: `anipy-cli -d frieren:1-3:sub (-f)` (optional ffmpeg arg)

**Comment by sdaqo** [comment]
you can already do that: `anipy-cli -D -s frieren:1-3:sub`

**Comment by GreatTeacherOni** [comment]
Ah ok this feature already exists. I just had to provide the search function to the Download or Binge Mode.
The help command shows: `Provide a search term to the Download or Binge mode in this format: {query}:{episode range}:{dub/sub}. Examples: 'frieren:1-10:sub' or 'frieren:1:sub' or 'frieren:1-3 7-12:dub'`

Could be an example command be appended to the info? Like `anipy-cli -D -s frieren:1-3:sub`

**Comment by sdaqo** [comment]
> Ah ok this feature already exists. I just had to provide the search function to the Download or Binge Mode. The help command shows: `Provide a search term to the Download or Binge mode in this format: {query}:{episode range}:{dub/sub}. Examples: 'frieren:1-10:sub' or 'frieren:1:sub' or 'frieren:1-3 7-12:dub'`
> 
> Could be an example command be appended to the info? Like `anipy-cli -D -s frieren:1-3:sub`

sure
