### ISSUE TITLE
[Request] Fix CI problems with arbitrary pypi package propagation time

### ISSUE THREAD

**Issue by GreatTeacherOni** [sdaqo/anipy-cli#181]
If poetry.lock file (in root, api and cli folder) is not updated on version bump it fails to build.

Following error occurs:
error: builder for '/nix/store/hr8s6dchmv0jfk3h23b6m4i5cg2vdgqk-python3.11-anipy-cli-3.1.7.drv' failed with exit code 1;
       last 10 log lines:
       > Creating a wheel...
       > * Getting build dependencies for wheel...
       > * Building wheel...
       > Successfully built anipy_cli-3.1.7-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for anipy_cli-3.1.7-py3-none-any.whl
       >   - anipy-api<4.0.0,>=3.1.7 not satisfied by version 3.1.6
       For full logs, run 'nix log /nix/store/hr8s6dchmv0jfk3h23b6m4i5cg2vdgqk-python3.11-anipy-cli-3.1.7.drv'.

Possible solution:
- Integrate lock file update into version bump commit
- Automatically add a lock file update commit (auto-commit) after version bump commit

**Comment by GreatTeacherOni** [comment]
I can fix it by running `poetry update` inside root, api and cli folder, but that leads to dirties my git repo since it changes from upstream

**Comment by GreatTeacherOni** [comment]
Ah i can see that "github-actions[bot]" is configured. Was there a problem with the last version bump why it didn't automatically ran to update the lock file?

**Comment by sdaqo** [comment]
This is already done, we auto commit a lock file update. The problem is slow package propagation on pypi, for example: the cli relies on the api (3.1.7) we push 3.7.1 to pypi repos, wait for 20 seconds for packages to propagate then we lock the cli and publish it. This does not always work because the time it takes is arbitrary. The only solution would be to implement a check that waits until the package is available.

**Comment by GreatTeacherOni** [comment]
Such a check sounds like a good solution

**Comment by sdaqo** [comment]
yup, I have it on my todo

**Comment by sdaqo** [comment]
Should be done in https://github.com/sdaqo/anipy-cli/commit/22aa83f406b69d889ad01f3bc8b59ddf624597bc, testing ci like this a little bit annoying, but lets hope it holds up.
