### ISSUE TITLE
Message about extraction of stream being spammed when title of episode too long

### ISSUE THREAD

**Issue by AxeldeWater** [sdaqo/anipy-cli#184]
**Describe the bug**
Whenever the title of the series + season + episode does not fit on one line in the window of the terminal emulator, the message about the stream being extracted (or something similar, I don't recall it exactly) is spammed in the terminal. 

**To Reproduce**
1. Make the terminal relatively small sized
2. Search for jojo
3. Select "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders 2nd Season (sub)"
4. Select a random episode and play
5. Many lines about "extracting the stream" are spammed in the terminal
6. Episode starts playing and menu appears like normally

**Expected behavior**
The line about the stream being extracted not being spammed. If there is not enough space for the title, it should either be cut-off at the end with dots or continue on the next line.

**Platform**
 - Using fish shell in gnome-terminal

**Comment by sdaqo** [comment]
I can reproduce this on alacritty, interesting. I do not know if I can directly do something about this as I am using a third-party library for the spinning progress thingy.

I will do some investigating tomorrow, if I do not find anything we can report this upstream.

**Comment by sdaqo** [comment]
There is already a issue in upstream: https://github.com/pavdmyt/yaspin/issues/131. I created a PR to fix this: https://github.com/pavdmyt/yaspin/pull/240. Will leave this open until the PR gets merged.

**Comment by AxeldeWater** [comment]
I looked into the PR. I'm interested in what your solution was. It looks like a quite clever solution.

**Comment by AxeldeWater** [comment]
@sdaqo the main developer of yaspin seemed to be on vacation for a while, but now seems to be back. Is it an idea to nudge him? Or do we just patiently wait? I don't know exactly what the norms are here on Github.

**Comment by sdaqo** [comment]
Well I guess bumping a PR is a little rude but as the repo has no  activity at all, it should be fine.

**Comment by sdaqo** [comment]
https://github.com/pavdmyt/yaspin/pull/240 got merged, will include the new yaspin version as soon as it is published
