### ISSUE TITLE
Downloader does not start from beginning

### ISSUE THREAD

**Issue by ItsChimmy** [sdaqo/anipy-cli#186]
**Describe the bug**

**To Reproduce**
1. Start anipy-cli in Seasonal mode "anipy-cli -S"
2. add a anime
3. When it asks you if you want to start from beginning by skipping the prompt skip it with ctrl z
4. press d to download
5. it starts downloading ep 2, as it thinks that ep 1 is already done

**Expected behavior**
It should start downloading from the first episode

**Info**
Post your output of `pip show anipy-cli`
(Using pipx)
⣻ upgrading anipy-clianipy-cli is already at latest version 3.1.8

**Platform**
 - OS: Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-41-generic x86_64

**Additional context**
None

**Comment by Quicksilver151** [comment]
I don't quite understand setp 3. Can it be detailed a little more.

**Comment by ItsChimmy** [comment]
Here is a video showing it [video](https://img.jhh.moe/r/p2wRMt.mp4)

https://github.com/user-attachments/assets/a576ceec-aa28-4646-b408-b9f355e0675c

**Comment by sdaqo** [comment]
fixed in 3.1.9
