### ISSUE TITLE
Change sub/dub not working properly

### ISSUE THREAD

**Issue by Anonimasu1** [sdaqo/anipy-cli#187]
I've been watching for the dubs to be released this season, and for the last 2 that have come out, when I try to switch using the change option, it returns that the dub is not available. If I manually search for that title it does give me the option to add the dub version to my seasonals list, so it can definitely see them.

In addition to the above issue, there was another bug I came across where I had Mushoku dub already in my seasonals list, and if I go into the option to change, select all titles with ctrl+a, and select dub, it would switch Mushoku from dub to sub. If I repeat the process again it would switch back to dub.

This might be a different problem that the 2 above, but when I first tried this feature out, I noticed that when switching it keeps the same episode number saved for progress. This is probably working as designed, but it should ask for a new start point when switching.

**Comment by sdaqo** [comment]
What is your primary provider, gogoanime, yugenanime?

**Comment by sdaqo** [comment]
Actually, ...  not experiencing any issues. Might be because there was just a new season, that said I would recommend you use yugenanime as they are generally very reliable and have accurate info as opposed to gogoanime.

**Comment by Anonimasu1** [comment]
I am using the default provider for the latest release, which I think is Yugen. I have 2 PCs both running Linux Mint and I experienced this on both of them.

I just tried it again with Vtuber and I am still getting the same result. I added the dub to my seasonals list. I tried switching to sub and it worked. I then tried switching to dub and it says that it is not available.
![Screenshot from 2024-07-26 19-03-08](https://github.com/user-attachments/assets/d1b20c57-29d6-483c-9fcf-06a95906d390)

**Comment by sdaqo** [comment]
Ok I will have another look, thanks for the additional detail

**Comment by sdaqo** [comment]
Sorry for the wait! Can you still reproduce? I tried to follow your steps, is that right and does this still not work for you. I btw tried with both gogo and yugen, both work.

https://github.com/user-attachments/assets/f16953a6-859a-4ad4-ad33-754f07d00895

**Comment by Anonimasu1** [comment]
I just updated to the latest release and tried again. I am still getting the error where it doesn't recognize dub when using the change feature with certain anime that it does recognize has a dub when you use the add feature. Specifically Vtuber Legend still gives me the error and Why Does Nobody Remember Me in This World. Alya does now work, that was one that didn't when I first opened this ticket. I also verified that My Deer Friend and Spice and Wolf also work as intended.
I included my config file in case there's anything in there that could offer any insight to this problem. I think the only things I changed are the save paths and to prefer dub. Just to make sure that setting it to prefer dub wasn't the problem, I tried it out with ' ' and still had this error.
![Screenshot from 2024-08-07 17-15-11](https://github.com/user-attachments/assets/ba50f324-5c1e-4197-b469-d032dbaa1638)
![Screenshot from 2024-08-07 17-23-59](https://github.com/user-attachments/assets/806dd97e-cb33-40b7-b395-2f6276dd7aaf)
[config.txt](https://github.com/user-attachments/files/16534809/config.txt)

**Comment by sdaqo** [comment]
Did you already try to delete and re-add the vtuber anime?

**Comment by Anonimasu1** [comment]
I thought that I had to add Vtuber, but I just tried deleting it and adding it fresh and now it is working as designed. I checked with Why Does Nobody Remember Me, I know I didn't add it fresh yesterday. It did not work when I first tried it. I deleted it and readded it and now it is also working as designed when changing between sub/dub. The others that I said were working yesterday I added them all fresh yesterday. As far as I can tell that issue has been resolved. Thanks for the help!

While I have a thread open, I'd like to point out that the sentence for when it's not available is structured wrong. "Dub is for [title] not available." Should be "Dub for [title] is not available." Not nearly as important as the sub/dub not switching properly obviously. Thanks again!

**Comment by sdaqo** [comment]
Yeah, that is because for the seasonal mode there are some things being cache (including available languages) in the seasonals.json file. I am aware of it and I do plan to include some more checks as the language choices may change over time.

**Comment by sdaqo** [comment]
And thanks for the correction!
