### ISSUE TITLE
Option (true or false) to auto search in season

### ISSUE THREAD

**Issue by Cananbolt** [sdaqo/anipy-cli#190]
As the title states, it will be very convenient to have the option (true or false) to automatically search animes in the season.

**Comment by DragonOfShuu** [comment]
Okay, I will say that there is actually already a seasonal mode available inside of anipy by using the `-S` flag. 

However, this mode doesn't allow you to immediately search by season. I'm going to work on another flag that allows you to start anipy with it asking for seasonal information, as well as the ability to provide the seasonal search info on the flag too. I'm also working on the ability to set a config option to season search immediately too. 

I'll make a pull request when I'm finished :)

**Comment by Cananbolt** [comment]
Understood, thank you so much for acknowledging and working on this request. :)
