### ISSUE TITLE
https://gogoanime3.co alternatives?

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#199]
https://gogoanime3.co has been blocked in my region out of the blue

is there another gogoanime copy site that is compatible with this one that i can change the link to?

temporary solution: proton vpn

**Comment by sdaqo** [comment]
If you are on v3, just use yuugen, if not then try changing the domain to "anitaku.pe", this is the new gogo domain if I recall correctly.

**Comment by Quicksilver151** [comment]
sadly seems like anitaku also is blocked
ill stick with vpn
thanks for the help
