### ISSUE TITLE
[anipy-api] Other-info always None when using get_info() in the gogoprovider.

### ISSUE THREAD

**Issue by quenzt** [sdaqo/anipy-cli#200]
**Describe the bug**
When calling `anime.get_info()` on an anime using the gogoprovider, the info-elements `status` , `release_year` and  `genres` are always assigned to their respective default values.
eg `status, release_year, genres = None, None, []`

**To Reproduce**
take a look at this mini script
```
from anipy_api.provider import list_providers, get_provider 
from anipy_api.anime import Anime
from anipy_api.provider import LanguageTypeEnum

provider = get_provider("gogoanime")
supported_lang = {LanguageTypeEnum.SUB: True, LanguageTypeEnum.DUB: True}
anime = Anime(provider, "Beastars", "beastars", supported_lang)
info = anime.get_info()
print(info.status)
```

**Expected behavior**
The above code prints `None`. One would expect it to print `Status.COMPLETED` as the anime is correctly marked as completed on gogoanime.

**Info**
```
Name: anipy-cli
Version: 3.2.1
Summary: Watch and Download anime from the comfort of your Terminal
Home-page: https://sdaqo.github.io/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /home/quenzt/newdl/anipy/lib/python3.12/site-packages
Requires: anipy-api, appdirs, inquirerpy, pypresence, pyyaml, yaspin
Required-by: 
```

**Platform**
 - OS:  tested on linux, but that probally doesn't affect the bug

**Additional context**
So I did a bit of digging and I think I found what the problem is here. In line 207-222 of [`gogo_provider.py`](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py),  the variable `cat_name` is checked against `"Genre:"`, `"Status:"`, and `"Released:"`. 
However cat_name assumes the values  `"Genre: "`, `"Status: "`, and `"Released: "`. 
Adding these 3 whitespaces to lines [210](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py#L210) [212](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py#L212) and [218](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py#L218), or stripping `cat_name` of whitespaces does indeed fully resolve this bug.

**Comment by sdaqo** [comment]
Sorry missed this report, will look into this

**Comment by sdaqo** [comment]
> So I did a bit of digging and I think I found what the problem is here. In line 207-222 of [gogo_provider.py](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py), the variable cat_name is checked against "Genre:", "Status:", and "Released:".
However cat_name assumes the values "Genre: ", "Status: ", and "Released: ".
Adding these 3 whitespaces to lines [210](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py#L210) [212](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py#L212) and [218](https://github.com/sdaqo/anipy-cli/blob/12ddeb81c41da4b621af9cfd55d36e35d329bd28/api/src/anipy_api/provider/providers/gogo_provider.py#L218), or stripping cat_name of whitespaces does indeed fully resolve this bug.

Awesome, wanna make a PR?
