### ISSUE TITLE
Newer versions of MPV issue

### ISSUE THREAD

**Issue by OneWiseKnight** [sdaqo/anipy-cli#204]
**Describe the bug**
While playing content the MPV window will freeze usually around the middle which has been happening for couple weeks.

**To Reproduce**
1. Install Anipy-cli via pipx
2. Using latest MPV type anipy-cli in terminal
3. Press N to skip search season
4. Search any anime and select any episode will play until 30-50% until freezing

**Expected behavior**
Expecting video to play the entire length.

**Info**
Result of pipx list:

package anipy-cli 3.2.2, installed using Python 3.12.7

**Platform**
 - Arch Linux

**Versions**
MPV: 1:0.39.0-1
Kernel: Linux 6.11.5-3
KDE Plasma: 6.2.2

**What has been tried with freezing still occurring**
- Fresh Arch installs with no modifications to mpv config or anipy-cli toml files
- tested cache=yes, cache=no, cache=auto

**Additional context**
The freezing will even occur if the cache is fully downloaded and cache state is EOF. Was using the mpv-git for months however that started to freeze couple months ago, and switching to the stable mpv worked until couple weeks ago.

**What works**
- VLC, MPV-Controlled
- Using the video info url produced by anipy-cli, typing in terminal 'mpv url' works just fine and video plays fully

**Comment by sdaqo** [comment]
Do other players work? Does downloading work? Please also post your config.

**Comment by sdaqo** [comment]
So I tried with the mpv version you mentioned, and I do not want to be that guy, but it works completely fine for me. Granted, I am on another platform (nixos).

Maybe also try to look if mpv is outputting anything when you are playing the video (press ` to open the console in mpv)

**Comment by OneWiseKnight** [comment]
Yes using anipy-cli, both VLC and MPV-Controlled work. As for trying `, I will try that.

**Comment by sdaqo** [comment]
Wait MPV-Controlled works? Now I am confused, there should be virtually no difference...

**Comment by OneWiseKnight** [comment]
I tried to search the code if there were variables being passed but did not find anything, and yes mp-controlled working is funny.

**Comment by sdaqo** [comment]
With the default config, the mpv command opened is this: `mpv <url> --force-media- title="<episode name>" --force-window=immediate --keep-open=no`

**Comment by sdaqo** [comment]
> edit: which version of mpv is nixos using?

The same one as you, 0.39.0, this is the newest version on the unstable channel.

**Comment by OneWiseKnight** [comment]
I think what I will do is try mpv through the terminal using those commands, and using the video url outside the anipy-cli script and see what happens.

**Comment by OneWiseKnight** [comment]
I have let the episode play for 22 mins with no freezing.

I took the print video info url from an episode in anipy-cli, and just went to the terminal and did the command as you posted and it went ok, so those variables aren't a problem. I guess my next step is try pip and not pipx.

**Comment by OneWiseKnight** [comment]
What I have tested...

:x: Pipx git version freezing still occured
:ok: MPV version 0.38.0-6 worked fine
:ok: MPV version 0.38.0-8 worked fine
:x: MPV version 0.39.0-1 freezing occured

Something changed in mpv in version 39

**Comment by sdaqo** [comment]
I will do some more investigating tomorrow, but honestly I am not sure to which extent this issue has something to do with anipy, but we will see.

**Comment by Katkidnapped** [comment]
I have this same issue on Arch Linux

**Comment by sdaqo** [comment]
> I also tried mov-cli which also uses pipx, and no freezing occurred. I tried to compare code for mpv players, however it is way over my head.

I looked into it, it works exactly the same, both projects are written in python and they use the same method to start the player.

> Here are two mpv output files for mpv 0.38 and mpv 0.39-git

0.39-git is the one that freezes right? I looked a bit into it, and of course it's hard to say as I did not see it myself but in line 4526 and 4527 in the 0.39 log file this is written
```
[ 292.370][v][lavf] cached range 0: 156.388167 <-> 170.986089 (bof=0, eof=0)
[ 292.370][v][lavf] cached range 1: 193.633711 <-> 1412.684878 (bof=0, eof=0)
```
This (should) indicates the cache ranges, and looking at that there is cache range from (converting from seconds) 2:36 to 2:50 and a range from 3:13 to  23:33, so considering that is a normal anime episode basically, in theory the whole thing should be cached and it **should** playback without issue.


I will check this on an arch distrobox maybe I can find something... (doubt it)

**Comment by OneWiseKnight** [comment]
Also one thing I forgot to mention, even when the cache reached EOF, meaning I let it buffer fully the freezing still occurred.

**Comment by sdaqo** [comment]
I am going to try bisect mpv and find the bad commit

**Comment by sdaqo** [comment]
This is the bad commit, I think I know how I can fix this:
```
f18ce7eca00a2ea384a5244c6b01e82e5ede0630 is the first bad commit
commit f18ce7eca00a2ea384a5244c6b01e82e5ede0630
Author: Kacper Michajłow <kasper93@gmail.com>
Date:   Sun May 5 16:38:02 2024 +0200

    msg: print all messages to one stream

    This reverts commit 4939570e17d4659944924ed6012793b433109ab1 and makes
    it more strict about the output stream. Status message is also on the
    same stream now.

 common/msg.c | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)
```

**Comment by sdaqo** [comment]
This is the first bad mpv commit:
```
f18ce7eca00a2ea384a5244c6b01e82e5ede0630 is the first bad commit
commit f18ce7eca00a2ea384a5244c6b01e82e5ede0630
Author: Kacper Michajłow <kasper93@gmail.com>
Date:   Sun May 5 16:38:02 2024 +0200

    msg: print all messages to one stream

    This reverts commit 4939570e17d4659944924ed6012793b433109ab1 and makes
    it more strict about the output stream. Status message is also on the
    same stream now.

 common/msg.c | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)
```
I think I know how to fix this

**Comment by sdaqo** [comment]
should be fixed in 3.2.3

**Comment by OneWiseKnight** [comment]
Tested on version 3.2.3 using MPV 1:0.39.0-1 Arch I can confirm to be working. :+1:

**Comment by sdaqo** [comment]
perfect, closing
