### ISSUE TITLE
anipy-cli incorrectly map Bokutachi wa Benkyou ga Dekinai

### ISSUE THREAD

**Issue by hillz2** [sdaqo/anipy-cli#207]
**Describe the bug**
I'm using anipy-cli version 3.2.3 with yugenanime as the download site (default), I added [Bokutachi wa Benkyou ga Dekinai season 1](https://myanimelist.net/anime/38186/Bokutachi_wa_Benkyou_ga_Dekinai?q=bokutachi&cat=anime) to my MAL watchlist but when I mapped it, it got mapped to [Bokutachi wa Benkyou ga Dekinai! season 2](https://myanimelist.net/anime/40004/Bokutachi_wa_Benkyou_ga_Dekinai) so the downloaded episodes are bokuben season 2 instead of season 1. Please fix it.

**To Reproduce**
2. Do This '...'

**Expected behavior**
Should be mapped to bokuben season 1 instead of season 2

**Info**
Post your output of `pip show anipy-cli`

**Platform**
 - OS: ubuntu 24.04
 - Maybe something else that is specific to your platform and may have impact on the bug

**Additional context**
Add any other context about the problem here, e.g. your config if related.

**Comment by sdaqo** [comment]
Please proper reproduction steps...
I can not reproduce this following your explanation it works just fine.

**Comment by hillz2** [comment]
1. Add [this anime](https://myanimelist.net/anime/38186/Bokutachi_wa_Benkyou_ga_Dekinai?q=bokutach&cat=anime) to the watchlist via the MAL website
2. `anipy-cli -M`
3. Choose `[m] Map MyAnimeList anime to providers` 
4. Then download the whole episode with `anipy-cli Ma`

It downloads the second season instead of the first one, note that the second season of bokuben has `!` in the title, that's probably what's causing the problem. I'm sure what you have downloaded is the second season of Bokuben instead of the first one, try to watch the episode if you don't believe me.

**Comment by sdaqo** [comment]
It's not that I don't believe you, I already saw this anime and the first episode was definitely season 1.  

That out of the way, It is possible that something like that happens, especially if the names only differ by one character. I do have an idea on how to make it stricter, but in the meantime set the `mal_mapping_min_similarity` config option to 1, then it will only map names that match 1:1, you will probably have to manually map more often though.

**Comment by hillz2** [comment]
How do I manually map an anime ?

**Comment by sdaqo** [comment]
It will prompt you if it can't map it

**Comment by sdaqo** [comment]
Check the config it's all explained in there

**Comment by hillz2** [comment]
Setting `mal_mapping_min_similarity` to `1` finally solved the problem, the default setting was `0.8`. Thanks
