### ISSUE TITLE
doesnt work when the program is run in a directory that contains a space

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#21]
error:
`python3: can't open file '/media/renderinguser/PC': [Errno 2] No such file or directory`

was just bout to test the seasonal thing in another directory when this happened

it only happens when running `anipy-cli` directly from the command line
it works when i run main.py manually

**Comment by sdaqo** [comment]
Did you do make install? Can you send anipy-cli file from /use/local/bin and the location of the anipy clo folder?

**Comment by Quicksilver151** [comment]
make installed works
just not running anipy-cli

i think thisll just be fixed if the directory is covered with `" "`

**Comment by sdaqo** [comment]
Oh I see probably your path contains a space. This will fix it, thanks I will do that later today.

**Comment by sdaqo** [comment]
Yeah sorry 😅 Anyways going to fix it.
