### ISSUE TITLE
Yugenanime & Gogoanime have stopped updating their episodes

### ISSUE THREAD

**Issue by hillz2** [sdaqo/anipy-cli#210]
https://gogoanime3.cc/ and https://yugenanime.tv/ have stopped updating their episodes, can you add another working provider to `anipy-cli` ? looks like they're about to be taken down https://www.reddit.com/r/animepiracy/comments/1h27w8d/gogoanime_might_shut_down/

**Comment by sdaqo** [comment]
well that sucks, I will look into adding another provider

**Comment by hillz2** [comment]
I suggest [animepahe](https://animepahe.ru/). It's the fastest at updating their episodes

**Comment by sdaqo** [comment]
Yeah will see if I can get around the DDoS guard for animepahe, I have also been looking into miruro .tv

**Comment by Quicksilver151** [comment]
ah sht

i was wondering what happened

will gogoanime ever come back?

**Comment by hillz2** [comment]
> ah sht
> 
> i was wondering what happened
> 
> will gogoanime ever come back?

doubt it'll come back, but usually new sites will pop up, they can never shut down piracy arr arr

**Comment by Quicksilver151** [comment]
welp, time to finally stop using anipy-cli v2 i guess

**Comment by hillz2** [comment]
> welp, time to finally stop using anipy-cli v2 i guess

can you recommend me another cli program to download anime ?

**Comment by hillz2** [comment]
> > > welp, time to finally stop using anipy-cli v2 i guess
> > 
> > 
> > can you recommend me another cli program to download anime ?
> 
> You can probably use ani-cli

from the github page, I don't think it supports downloading anime, I watch anime on jellyfin so I have to download it first

**Comment by hillz2** [comment]
> It should support it? Haven't used it in a while, but I think it did support it.

no, I've tried it on ubuntu running inside docker, doesn't work, it just skips the episode. I've been using anipy-cli for a long time actually, I guess I just have to wait

**Comment by Quicksilver151** [comment]
> > welp, time to finally stop using anipy-cli v2 i guess
> 
> can you recommend me another cli program to download anime ? 

V3 when it starts working again (hopefully)

**Comment by sdaqo** [comment]
> hopefully

Yeah, no I am pretty certain that it will start working again, just need some time as I currently have a couple of exams, expect some updates in the next few weeks, or maybe sooner if I find some time

**Comment by candrapersada** [comment]
if possible, support 360p quality

**Comment by sdaqo** [comment]
now then, 3.3.0 is out and we got a new provider, I will look into adding more providers so that something like this does not happen again, but for now we are good
