### ISSUE TITLE
CrunchyRoll API 

### ISSUE THREAD

**Issue by Sweetkubuni** [sdaqo/anipy-cli#213]
With the current issue of #210  and #212 mentioning providers being down, could we have a premuim api like crunchyroll as an alternative option? I know projects like https://github.com/crunchy-labs/crunchyroll-go could be use as an example.

**Comment by Sweetkubuni** [comment]
actually never I just saw their cli stated the DRM issue

**Comment by sdaqo** [comment]
Yeah, Crunchyroll apis are kinda dead, you would have to break the encryption, and I don't want my project taken down by them.
