### ISSUE TITLE
Change the way the program queues downloads

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#24]
This is probably gonna be a big change in the internal workings of the program so i was initially not gonna raise the issue but now ive faced quite a lot of problems with this being the way it is.
suppose i queue like 100 episodes of one piece to download,
first, the program fetches the links for all the 100 episodes
and only after that, it start to download the episodes
The problem with that is, by the time it downloads like 10 episodes or such, the rest of the download links all expire. I personally wouldnt have much of a problem of being able to download 10 episodes at a time but...
As for me and my awful internet connection, i can barely queue 4 episodes right now

So, would it be possible to make it so that the program only fetches the link of the episode it attempts to download, only when it needs to download the episode?

**Comment by sdaqo** [comment]
Yeah that makes sense. Did it now, wasn't that  much of a change. Could you try it out?

**Comment by Quicksilver151** [comment]
oh hey
well that works perfectly now
