### ISSUE TITLE
[Feature request] Separate path for seasonals download

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#26]
so... my downloads folder is a bit hard to navigate rn so would it be possible to give seasonals a separate download path?
and also make the seasonals download path modifyable in config.py

**Comment by sdaqo** [comment]
How about separate path for every anime?

**Comment by Quicksilver151** [comment]
thats.....
even better
but still id like a folder to separate seasonal with other stuff downloaded

**Comment by sdaqo** [comment]
I did this now, not the folder per anime (maybe I will do this another time), but the seasonal dl folder.

**Comment by Quicksilver151** [comment]
just need one small fix for the text here
`Do you want to download these/this episode(s)? (y/N)`
since y is default, capitalize the y instead of n
(this specific message is from the seasonals download)

**Comment by sdaqo** [comment]
Ok, will close this now.
