### ISSUE TITLE
Link debugging, and better link handling 

### ISSUE THREAD

**Issue by sdaqo** [sdaqo/anipy-cli#32]
This is mentioned in #28. Anyone that finds something, please post it here.

**Comment by sdaqo** [comment]
Regarding the peliscdn links: 
When fetching you get a m3u8 playlist with more m3u8 playlist link will look something like this: 
https://peliscdn/.../.../playlist.m3u8, in this link there are more playlists that each point to a different quality (qualitys are not given in the json respones of the ajax which makes it somewhat annoying), which then contain the ts links (parts of the video).  Just info about this I wanted to post here.

**Comment by Dankni95** [comment]
Worst quality sometimes are not filled out/non existent, this is probably why i had problems last time:
![image](https://user-images.githubusercontent.com/71786017/156222822-99278b53-e5c9-4338-b5f9-c2407177f8ba.png)

Removing all empty entries in quality_links solves this problem. I think :+1: 

The links are bit slow at fetching for my liking tho!

**Comment by Dankni95** [comment]
The pediscdn links are very slow when downloading it seems! Have not debugged download implementation tho.

**Comment by sdaqo** [comment]
> Worst quality sometimes are not filled out/non existent, this is probably why i had problems last time:

Yeah noticed this as well, will patch it tomorrow or so.

**Comment by Quicksilver151** [comment]
just here to thank yall for getting the seasonals mode done
been waiting for that
but now i probably gotta go and convert my previous seasonals file into the new json format 
hopefully this change will also be deployed?

**Comment by sdaqo** [comment]
> just here to thank yall for getting the seasonals mode done

No need to thank, we do this for fun.

 > hopefully this change will also be deployed?

What exactly do you mean?

**Comment by Quicksilver151** [comment]
deployed to pip

also could you format the json file to not all be in one line?

**Comment by sdaqo** [comment]
> deployed to pip
It already is, maybe try anipy-cli==2.2.0

> also could you format the json file to not all be in one line?

Just go on Google and search for Json formatter they are all over the place, I don't think its necessary.

> edit: also m3u8 playlist are still ignoring the selected resolution again

Well, I can't do a lot about that, what will probably work is best/worst.

**Comment by Quicksilver151** [comment]
ok so m3u8 still doesnt download entirely for me

maybe i could just download those manyally
so could you make seasonals first show the anime it can download before starting to download?

**Comment by sdaqo** [comment]
> ok so m3u8 still doesnt download entirely for me

Yeah I also noticed this yesterday, I will see if I can debug that


> so could you make seasonals first show the anime it can download before starting to download?

Yeah I can do that, like the old function right?

**Comment by sdaqo** [comment]
HI, now that took way to long, downloads should be finishing now. Debugged this for way too long, and turns out I am just stupid. Anyways sorry for the long wait.

**Comment by sdaqo** [comment]
ffmpeg is now there as optional option so we dont have to deal with gogoanime changing things
