### ISSUE TITLE
Gogo changed algo again

### ISSUE THREAD

**Issue by Dankni95** [sdaqo/anipy-cli#35]
If anyone want to go ahead and implement this:

https://github.com/justfoolingaround/animdl/blob/e1ac9e43f8a317f2623b65f47cf1aabbbdd9a665/animdl/core/codebase/extractors/gogoplay/__init__.py

or wait for ani-cli to implement their version as our is pretty similar. I dont have time right now, but may have some time later today!

**Comment by sdaqo** [comment]
Will do it

**Comment by Dankni95** [comment]
Ani-clis fix: https://github.com/pystardust/ani-cli/pull/563/files

Did not test it, but looks to be working solution

**Comment by sdaqo** [comment]
did it

**Comment by Dankni95** [comment]
Well done, you were quick, im not as good with bfsoup so were struggling :+1:
