### ISSUE TITLE
places files in a location with admin privilages?

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#38]
```bash
python3 ./run_anipy_cli.py 
Traceback (most recent call last):
  File "./run_anipy_cli.py", line 2, in <module>
    from anipy_cli import cli
ModuleNotFoundError: No module named 'anipy_cli'
```

**Comment by sdaqo** [comment]
You have to pip install it to run this file, did you do that?

**Comment by Quicksilver151** [comment]
> You have to pip install it to run this file, did you do that?

i did python3 ./setup.py install

**Comment by sdaqo** [comment]
Go in the repo and execute `pip install .`
Or just do `pip install anipy-cli` it is on the papi repos, you then can just do anipy-cli and it works automaticlly.

**Comment by Quicksilver151** [comment]
the problem is this
`Downloads are stored in: /home/renderinguser/.local/lib/python3.8/site-packages/anipy_cli/download`
its storing files in an admin location

**Comment by Quicksilver151** [comment]
and its fetching the maximum resolution again

**Comment by sdaqo** [comment]
> would there be a way to change the path it downloads to?

It downloads to the default python install path for pip packages you can look In docs/install.md for more options

**Comment by sdaqo** [comment]
> and its fetching the maximum resolution again
> i selected 720 but its downloading 1080

idk why maybe 720 is not available, could you give me the anime so I can check it later

**Comment by Quicksilver151** [comment]
```
Downloading: Shingeki no Kyojin: The Final Season Part 2 EP: 9 - 480p 
Type: m3u8
```
this is what the output says
but the parts being downloaded are all 1080p

**Comment by sdaqo** [comment]
Hmm thats weird, it downloads a mp4 for me, maybe the link on gogoganime really were cuorrupt. The file is alse 720 (also tried for 480p). Could you try again?
```--------------------
Downloading: Shingeki no Kyojin: The Final Season Part 2 EP: 9 - 720p 
Type: mp4
```

**Comment by Quicksilver151** [comment]
ok its mp4 now for some reason
it used to be a m3u8 playlist
guess the server changed

**Comment by sdaqo** [comment]
Ha... Just working on this, just some fine tuning and it will be finished.
