### ISSUE TITLE
Episode not playing

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#40]
For the last 2 days, I am unable to play anything with this. I am able to search with the program, So I don't think its a problem of DNS resolve. However, attempting to play an episode gives me an error likes and quits out.
```
anipy-cli: error: could not locate crypto: https://gogoplay5.com/streaming.php?id=MTgzMzA2&title=Sabikui+Bisco+Episode+12&typesub=SUB
```

Funnily enough even playing through youtube-dl or yt-dlp quits on me like this

```
>yt-dlp.exe "https://gogoplay5.com/streaming.php?id=MTgzMzA2&title=Sabikui+Bisco+Episode+12&typesub=SUB"
[generic] streaming: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] streaming: Downloading webpage
[generic] streaming: Extracting information
ERROR: Unsupported URL: https://gogoplay5.com/streaming.php?id=MTgzMzA2&title=Sabikui+Bisco+Episode+12&typesub=SUB
```

Anyone else facing any similar issues?

**Comment by sdaqo** [comment]
Yeah thanks for reporting this, looks like there was a change on ajax system on gogo, I will Implement a fix as soon as possible.

**Comment by sdaqo** [comment]
Fix is now implemented could you try again and report back? You will have to uninstall your old anipy-cli and install it again like so: `python3 -m pip install git+https://github.com/sdaqo/anipy-cli`, I will push it later to pypi

**Comment by Prashanthvsdvn** [comment]
Hey sorry I couldn't report it back immediately. The fix works. Closing the issue. Thank you!!!
