### ISSUE TITLE
Download does not complete again

### ISSUE THREAD

**Issue by Quicksilver151** [sdaqo/anipy-cli#41]
when downloading m3u8 files, downloading parts stop after reaching around 80% again
every
time

in addition, the temporary directory containing the .ts files contain not just video clips but also files containing:
```html
<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;50&#46;1feb1cb8&#46;1648791032&#46;bb92fec0
</BODY></HTML>
```

is this an issue due to my network or something else?

**Comment by sdaqo** [comment]
Maybe it has something to do with #40 i. e. Gogo changed something. I will look into this later today when I'm home.q

**Comment by sdaqo** [comment]
Could you give me an example, where it didnt work, because I tried it with both aot last ep and my dress up darling last ep, both m3u8 and it worked.

**Comment by Quicksilver151** [comment]
i guess then its probably just an issue of network speed
oh well
