### ISSUE TITLE
[Exception] Message: TypeError: document.getElementsByClassName(...)[2] is undefined

### ISSUE THREAD

**Issue by WubzyGD** [sdaqo/anipy-cli#5]
Just installed anipy-cli.

I think this screenshot explains it best:

![image](https://user-images.githubusercontent.com/63122940/147662055-829bcfff-7082-42d1-b4ef-423c64c686f1.png)

Know of any fix?

**Comment by sdaqo** [comment]
please just try again it should work, at my side it does at least

**Comment by WubzyGD** [comment]
yep still same error. tried a different anime as well

**Comment by sdaqo** [comment]
Could you try to add `time.sleep(5)` to src/url.py in line 48 and then try again.

**Comment by WubzyGD** [comment]
well that worked but now the episode isn't playing again
![image](https://user-images.githubusercontent.com/63122940/147664120-b9e1d79b-158e-453a-ad39-fd245f08400c.png)

**Comment by WubzyGD** [comment]
wait no i lied wrong terminal; bashrc still has my `anime` alias for `ani-cli`. it works, thanks!

**Comment by sdaqo** [comment]
Ok thats nice. The problem above is probably caused by the website not loading. I was going to implement something like "wait till website is loaded", but never did it because it was working fine for me. I  will try to  implement it.

**Comment by WubzyGD** [comment]
sweet! let me know if you do!
