### ISSUE TITLE
`anipy-cli -H` does not seem to be working

### ISSUE THREAD

**Issue by Dabbing-Guy** [sdaqo/anipy-cli#53]
**Describe the bug**
When using `anipy-cli -H`, attempting to pick a show cause an error to be raised.

**To Reproduce**
1. Run `anipy-cli -H`
2. Enter a valid number
3. Press enter
4. See the error

**Expected behavior**
`anipy-cli` plays the episode showed in the history. Or whatever the history function is supposed to do.

**Info**
```
Name: anipy-cli
Version: 2.4.12
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: /home/michael/.local/lib/python3.10/site-packages
Requires: better-ffmpeg-progress, bs4, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, requests, tqdm
Required-by:
```

**Platform**
 - OS: Bedrock Linux (With packages mainly from Artix, an Arch based distro)
 - Python Version: 3.10.4
 - Fresh install of anipy-cli from PyPI (installed with `pip install anipy-cli`) 

**Additional context**
Output of the error:
```
❯ anipy-cli -H
[1] EP: 1 | Sword Art Online (Dub)
Enter Number: 1
Traceback (most recent call last):
  File "/home/michael/.local/bin/anipy-cli", line 8, in <module>
    sys.exit(main())
  File "/home/michael/.local/lib/python3.10/site-packages/anipy_cli/run_anipy_cli.py", line 8, in main
    cli.main()
  File "/home/michael/.local/lib/python3.10/site-packages/anipy_cli/cli.py", line 650, in main
    history_cli(args.quality, player)
  File "/home/michael/.local/lib/python3.10/site-packages/anipy_cli/cli.py", line 168, in history_cli
    menu(show_entry, options, sub_proc, quality).print_and_input()
TypeError: menu.__init__() missing 1 required positional argument: 'player'
```

**Comment by sdaqo** [comment]
Thanks for reporting! I forgot this in the last feature in [this](https://github.com/sdaqo/anipy-cli/commit/7742c8d2e82023b4f50e2736a766de2bfb4f0ff2) commit.
