### ISSUE TITLE
Unable to play video

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#57]
**Describe the bug**
Selecting the episode to play crashes the program.

**To Reproduce**
1. Run the command
2. Search for an anime
3. Select an episode number

**Expected behavior**
The command should fetch link and play it in mpv

**Info**
WARNING: Ignoring invalid distribution -nipy-cli (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
Name: anipy-cli
Version: 2.4.14
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: c:\python310\lib\site-packages
Requires: better-ffmpeg-progress, bs4, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, requests, tqdm
Required-by:

**Platform**
 - OS: Windows

**Additional context**
Attaching error message
```
Search: spy x family
[1] Spy x Family
[2] Spy x Family (Dub)
Enter Number: ←[36m1
←[0mEpisode ←[92m[1-9]←[0m: ←[36m9
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\anipy-cli.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\anipy_cli\run_anipy_cli.py", line 8, in main
    cli.main()
  File "C:\Python310\lib\site-packages\anipy_cli\cli.py", line 656, in main
    default_cli(args.quality, player)
  File "C:\Python310\lib\site-packages\anipy_cli\cli.py", line 47, in default_cli
    sub_proc = start_player(show_entry, rpc_client, player)
  File "C:\Python310\lib\site-packages\anipy_cli\player.py", line 60, in start_player
    sub_proc = sp.Popen(player_command)
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Dabbing-Guy** [comment]
It works for me on windows. Are you sure you have mpv installed? If you don't, you can get it from Sourceforge with [this link](https://sourceforge.net/projects/mpv-player-windows/files/latest/download). Unzip the folder, run the updater.bat file, and press y on all of the prompts and 1 for installing yt-dlp. Then copy the bootstrapper folder that contains the mpv files and move it to program files and name it MPV. Then add the newly move folder in program files to path (google it if you don't know how). 

If it does not work after doing that, tell me.

**Comment by Prashanthvsdvn** [comment]
I have fork of mpv installed called mpv.net I was using all these days without problem. The problem started today with anipy-cli telling it was unable to find token or something. but I haven't able to reproduce that back. Now it spits back the error I have mentioned in the log. I will try installing mpv and running with it.

**Comment by sdaqo** [comment]
It looks like mpvnet has all the commands mpv can use as well so you could just specify it in the config in the `player_path` path variable, so instead of `mpv` put `mpvnet`

**Comment by Prashanthvsdvn** [comment]
I tried with vanilla mpv, the program works without issue. I was at version 2.4.11 which worked without issue with mpv.net, until it started showing errors with not finding a token. I had updated to 2.4.14 afterwards, which had rewritten the config file I guess and started throwing these errors. @sdaqo can you add mpv.net to the player_path please? and we can close this issue

**Comment by sdaqo** [comment]
OK, should be added now in version 2.4.16
