### ISSUE TITLE
Issues with .5 episodes

### ISSUE THREAD

**Issue by Prashanthvsdvn** [sdaqo/anipy-cli#64]
I am not sure if this accounts as an bug or an PR. but we need to address how the program interacts with special episodes (usually has an episode numbers with .5 decimal)

**Describe the bug**
The current program doesn't identify .5 episodes and incorrectly maps the special episodes as regular episodes.

**To Reproduce**
1. Run program
2. Search for '86 Part 2' (not the dub)
3. Select Episode 6
4. Episode 6.5 starts playing instead

**Expected behavior**
The program should play regular episode (episode 6) instead of special episode (episode 6.5). 
If i recall correctly, the URL has an '-5' added to the end.

**Info**
```
Name: anipy-cli
Version: 2.4.18
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: c:\python310\lib\site-packages
Requires: better-ffmpeg-progress, bs4, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, requests, tqdm
Required-by:
```

**Platform**
 - OS: Windows 10

**Additional context**
Things I think the program should do
1. The program maps the regular and .5 episodes correctly
2. The episode selection UI should indicate presence and allow selection of .5 episodes

I detected this with 86 first but check with other series with .5 episodes in between.
Ideally, gogo should categorize them as special episodes but here we are.

**Comment by sdaqo** [comment]
Thanks for that info, I will have to look into that.

**Comment by sdaqo** [comment]
Added in [2.4.19](https://pypi.org/project/anipy-cli/2.4.19/)

**Comment by Prashanthvsdvn** [comment]
The same one 86 part 2. It has 4 specials and one of them is numbered 21.5.

**Comment by sdaqo** [comment]
Are you sure about that? Because gogo doesn't serve episode 21.5.  Maybe its some extra special, not included there.
![image](https://user-images.githubusercontent.com/63876564/175123739-a0fb16c9-70b3-48e7-b20b-e73f9f8256fd.png)

**Comment by Prashanthvsdvn** [comment]
Sorry, I was checking with some alternate gogo domain or clone. The one the script parses has the same thing as yours. My bad. Closing it.
