### ISSUE TITLE
How are u able to download anime?

### ISSUE THREAD

**Issue by liquidride** [sdaqo/anipy-cli#87]
Hello, i am trying to write anime scraper too! However i am having trouble downloading because there is ReCAPTCHA on download page... for example: https://gogohd.net/download?id=MTkyMjA=&typesub=Gogoanime-SUB&title=Hellsing+Episode+1 i am just wondering how are u able to bypass ReCAPTCHA ??

**Comment by sdaqo** [comment]
We dont use the download function, we use the internal rest api from gogo. Look [here in the code](https://github.com/sdaqo/anipy-cli/blob/5a8cc2059c31eb7eee15977355e0a1e91e0da8de/anipy_cli/url_handler.py#L335)

**Comment by sdaqo** [comment]
Though, quite frankly, i would advise you to use a diffrent provider, scraping gogoanime is a pain.

**Comment by liquidride** [comment]
i was looking into other websites , but could not find anything , do u know maybe for diffrent  provider?

**Comment by sdaqo** [comment]
I looked a bit, seems like [animepahe.com](https://animepahe.com/) may be pretty good. They dont have cloudlflare, recaptcha etc.. If you need any help, dont hestitate to ask, getting into webscraping isnt quite easy.

**Comment by liquidride** [comment]
cool tnx!
