### ISSUE TITLE
Discussion: Deprecate makefile

### ISSUE THREAD

**Issue by Dabbing-Guy** [sdaqo/anipy-cli#90]
The `makefile` still exist and is pretty useless now that we can install the project with pip. I think we should just delete it to avoid confusion if anyone tries to use it. Thoughts?

**Comment by sdaqo** [comment]
Sure, we can also delete the windows Istaller then. You want to make a PR, could do it as well later if you dont?

**Comment by Dabbing-Guy** [comment]
I can do that tomorrow

**Comment by sdaqo** [comment]
Ok, I will do it then, when I have time today.
