### ISSUE TITLE
Error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by raymonddong** [sdaqo/anipy-cli#96]
**Describe the bug**
Can't stream any episode. 
This error occurs: 
C:\Users\raymo\Documents\GitHub\anipy-cli>python3 anipy_cli.py
Search: Bocchi
[1] Cybot Robocchi
[2] Bocchi the Rock!
[3] Hitoribocchi no OO Seikatsu
[4] Mayonaka no Occult Koumuin: Hitoribocchi no Kyuuketsuki
[5] Mayonaka no Occult Koumuin: Hitoribocchi no Kyuuketsuki (Dub)
Enter Number: 2
Episode [1-12]
>> 1
Error: [WinError 2] The system cannot find the file specified

**To Reproduce**
1. See steps above^

**Expected behavior**
Expecting video player to open

**Info**
C:\Users\raymo\Documents\GitHub\anipy-cli>pip show anipy-cli
Name: anipy-cli
Version: 2.5.7
Summary: Little tool in python to watch anime from the terminal (the better way to watch anime)
Home-page: https://github.com/sdaqo/anipy-cli
Author: sdaqo
Author-email: sdaqo.dev@protonmail.com
License: GPL-3.0
Location: C:\Users\raymo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
Requires: beautifulsoup4, better-ffmpeg-progress, kitsu.py-extended, m3u8, moviepy, pycryptodomex, pypresence, python-dateutil, pyyaml, requests, setuptools, tqdm
Required-by:

**Platform**
 - OS: Windows

**Additional context**

**Comment by sdaqo** [comment]
Can you try running it with just `anipy-cli` instead of `python3 anipy_cli.py`? It seems you have already installed it anyway, no need to run it from the file directly.

**Comment by raymonddong** [comment]
It doesn't recognize it as a program when I try:

C:\Users\raymo\Documents\GitHub\anipy-cli>anipy-cli
'anipy-cli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Dabbing-Guy** [comment]
What is the output of `echo %path%` ran in cmd

**Comment by raymonddong** [comment]
Am I missing a path? If so what do I need?

C:\Users\raymo\Documents\GitHub\anipy-cli>echo %PATH:;=&echo.%
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\MATLAB\R2016b\bin
C:\Program Files (x86)\PuTTY\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\dotnet\
C:\WINDOWS\System32\OpenSSH\
C:\Users\raymo\AppData\Local\Microsoft\WindowsApps
C:\Users\raymo\AppData\Local\GitHubDesktop\bin
C:\Users\raymo\AppData\Local\Microsoft\WindowsApps
C:\Program Files\Java\jdk-1.8.0

**Comment by Dabbing-Guy** [comment]
in order to be able to run anipy-cli from the command line, pip makes an exe for it on installation. 
I can't remember where they are stored on windows exactly. Can you see if `C:\Users\raymo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\scripts` exists?

**Comment by raymonddong** [comment]
Yeah it does exist.
I tried running the exe from that folder and still shows the same error

**Comment by Dabbing-Guy** [comment]
Well, I guess you can add it to path for convenience. I'll boot into windows and try to replicate and fix this.

**Comment by Dabbing-Guy** [comment]
The error is caused by anipy-cli not being able to run mpv.

You don't seem to have mpv on your path, so this makes sense. Make sure you install mpv and add it to your path

**Comment by raymonddong** [comment]
It works now after I added mpv to my env path.
Thank you so much!
